[package]
name = "props_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.4"
lazy_static = "1.4.0"
regex = "1.10.2"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
log = "0.4.20"
